name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "@DeltaKroneckerGithub_Clash_369"
    type: ss
    server: "82.38.31.213"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "k1dBOmOB4oqi7Ump37a1bQ"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_371"
    type: ss
    server: "82.38.31.7"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_373"
    type: ss
    server: "67.219.106.119"
    port: 26286
    cipher: "chacha20-ietf-poly1305"
    password: "xfscSDcb-SeEqqRb.omzVGgVgNpXh3bA1u"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_375"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_377"
    type: ss
    server: "82.38.31.10"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_379"
    type: ss
    server: "82.38.31.16"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_381"
    type: ss
    server: "82.38.31.218"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "k1dBOmOB4oqi7Ump37a1bQ"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_383"
    type: ss
    server: "82.38.31.189"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "k1dBOmOB4oqi7Ump37a1bQ"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_385"
    type: ss
    server: "82.38.31.216"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "k1dBOmOB4oqi7Ump37a1bQ"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_387"
    type: ss
    server: "82.38.31.11"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_389"
    type: ss
    server: "198.98.53.130"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "eDfN7SODQceIOmIAbtJJtK"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_391"
    type: ss
    server: "82.38.31.193"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "k1dBOmOB4oqi7Ump37a1bQ"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_393"
    type: ss
    server: "172.234.202.34"
    port: 24833
    cipher: "chacha20-ietf-poly1305"
    password: "hRd=IXkjozMEKLeGR_0q09jtwly5J2la2O"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_395"
    type: ss
    server: "82.38.31.17"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_397"
    type: ss
    server: "140.174.184.5"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "qItG8SueYQcP"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_399"
    type: ss
    server: "82.38.31.35"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_401"
    type: ss
    server: "104.156.233.234"
    port: 27116
    cipher: "chacha20-ietf-poly1305"
    password: "bIOoi5TuImG2KccxV7-jcA7Cez+vun-c_E"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_403"
    type: ss
    server: "185.246.153.12"
    port: 31348
    cipher: "chacha20-ietf-poly1305"
    password: "ezyeH22iGS1UDeew5zzbTimqecrGBKSS1IsEqh"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_405"
    type: ss
    server: "108.181.58.239"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "CJmTCCx7Ltud"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_407"
    type: ss
    server: "r3mrcg001269pz2.cybervena.com"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "7e731ec3-f8e1-43f6-92cf-3978d14705c4"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_409"
    type: ss
    server: "103.111.114.80"
    port: 28061
    cipher: "chacha20-ietf-poly1305"
    password: "WOir3lXBhMHDcLFPQdEZXPu37_pTQDCXfm"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_411"
    type: ss
    server: "82.38.31.176"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "k1dBOmOB4oqi7Ump37a1bQ"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_413"
    type: ss
    server: "61.171.92.202"
    port: 1001
    cipher: "aes-256-gcm"
    password: "123"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_415"
    type: ss
    server: "36.230.9.156"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "7e731ec3-f8e1-43f6-92cf-3978d14705c4"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_417"
    type: ss
    server: "141.227.152.129"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "VJeAjiJ40F2Il17Elv285W"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_419"
    type: ss
    server: "193.47.60.186"
    port: 28687
    cipher: "chacha20-ietf-poly1305"
    password: "yKVMoB3AwiTEznpnoq2FYR"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 10
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_369"
      - "@DeltaKroneckerGithub_Clash_371"
      - "@DeltaKroneckerGithub_Clash_373"
      - "@DeltaKroneckerGithub_Clash_375"
      - "@DeltaKroneckerGithub_Clash_377"
      - "@DeltaKroneckerGithub_Clash_379"
      - "@DeltaKroneckerGithub_Clash_381"
      - "@DeltaKroneckerGithub_Clash_383"
      - "@DeltaKroneckerGithub_Clash_385"
      - "@DeltaKroneckerGithub_Clash_387"
      - "@DeltaKroneckerGithub_Clash_389"
      - "@DeltaKroneckerGithub_Clash_391"
      - "@DeltaKroneckerGithub_Clash_393"
      - "@DeltaKroneckerGithub_Clash_395"
      - "@DeltaKroneckerGithub_Clash_397"
      - "@DeltaKroneckerGithub_Clash_399"
      - "@DeltaKroneckerGithub_Clash_401"
      - "@DeltaKroneckerGithub_Clash_403"
      - "@DeltaKroneckerGithub_Clash_405"
      - "@DeltaKroneckerGithub_Clash_407"
      - "@DeltaKroneckerGithub_Clash_409"
      - "@DeltaKroneckerGithub_Clash_411"
      - "@DeltaKroneckerGithub_Clash_413"
      - "@DeltaKroneckerGithub_Clash_415"
      - "@DeltaKroneckerGithub_Clash_417"
      - "@DeltaKroneckerGithub_Clash_419"


rules:
  - MATCH,PROXY
