name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
<<<<<<< Updated upstream
  - name: "@DeltaKroneckerGithub_Clash_92"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f8c8dc3d-0d37-46b0-8b34-a7232882fcfe"
    alterId: 0
    cipher: "aes-128-gcm"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_94"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "e7d72a8d-26f2-4b54-b366-0c43e0bcba7d"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_96"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/linkvws"
  - name: "@DeltaKroneckerGithub_Clash_98"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "d13fc2f5-3e05-4795-81eb-44143a09e552"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_100"
=======
  - name: "@DeltaKroneckerGithub_Clash_266"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "cd682302-c9d7-4c0d-bada-52e7d652c22c"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_268"
>>>>>>> Stashed changes
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "d13fc2f5-3e05-4795-81eb-44143a09e552"
    alterId: 0
    cipher: "auto"
    udp: true
<<<<<<< Updated upstream
  - name: "@DeltaKroneckerGithub_Clash_102"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "d13fc2f5-3e05-4795-81eb-44143a09e552"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_104"
=======
  - name: "@DeltaKroneckerGithub_Clash_270"
>>>>>>> Stashed changes
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f8c8dc3d-0d37-46b0-8b34-a7232882fcfe"
    alterId: 0
    cipher: "auto"
    udp: true
<<<<<<< Updated upstream
  - name: "@DeltaKroneckerGithub_Clash_106"
=======
  - name: "@DeltaKroneckerGithub_Clash_272"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "04621bae-ab36-11ec-b909-0242ac120002"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_274"
>>>>>>> Stashed changes
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f8c8dc3d-0d37-46b0-8b34-a7232882fcfe"
    alterId: 0
    cipher: "auto"
    udp: true
<<<<<<< Updated upstream
  - name: "@DeltaKroneckerGithub_Clash_108"
=======
  - name: "@DeltaKroneckerGithub_Clash_276"
>>>>>>> Stashed changes
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "d13fc2f5-3e05-4795-81eb-44143a09e552"
    alterId: 0
    cipher: "auto"
    udp: true
<<<<<<< Updated upstream
  - name: "@DeltaKroneckerGithub_Clash_111"
=======
  - name: "@DeltaKroneckerGithub_Clash_278"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "a2170d39-140a-47f9-85b8-084078856c36"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/api/v1"
  - name: "@DeltaKroneckerGithub_Clash_280"
>>>>>>> Stashed changes
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f8c8dc3d-0d37-46b0-8b34-a7232882fcfe"
    alterId: 0
    cipher: "auto"
    udp: true
<<<<<<< Updated upstream
  - name: "@DeltaKroneckerGithub_Clash_113"
=======
  - name: "@DeltaKroneckerGithub_Clash_282"
>>>>>>> Stashed changes
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "inna.cfd"
    network: ws
    ws-opts:
      path: "/linkvws"
      headers:
        Host: "inna.cfd"
<<<<<<< Updated upstream
=======
  - name: "@DeltaKroneckerGithub_Clash_284"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "d13fc2f5-3e05-4795-81eb-44143a09e552"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_286"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "e7d72a8d-26f2-4b54-b366-0c43e0bcba7d"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_288"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f8c8dc3d-0d37-46b0-8b34-a7232882fcfe"
    alterId: 0
    cipher: "aes-128-gcm"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_290"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "04621bae-ab36-11ec-b909-0242ac120002"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_293"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "04621bae-ab36-11ec-b909-0242ac120002"
    alterId: 1
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_295"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "d8a706d0-9f21-46b8-9c08-f826b7799c77"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    client-fingerprint: "chrome"
  - name: "@DeltaKroneckerGithub_Clash_297"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "127.0.0.1"
    network: ws
    ws-opts:
      path: "/linkvws"
  - name: "@DeltaKroneckerGithub_Clash_299"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "d13fc2f5-3e05-4795-81eb-44143a09e552"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_301"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "d13fc2f5-3e05-4795-81eb-44143a09e552"
    alterId: 0
    cipher: "auto"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_303"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "4b80aa86-4354-40bb-d2a3-47126cff0bea"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "usaapp1.jisuyun.top"
    network: ws
    ws-opts:
      path: "/usavm"
      headers:
        Host: "usaapp1.jisuyun.top"
  - name: "@DeltaKroneckerGithub_Clash_305"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "f8c8dc3d-0d37-46b0-8b34-a7232882fcfe"
    alterId: 0
    cipher: "auto"
    udp: true
>>>>>>> Stashed changes

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
<<<<<<< Updated upstream
      - "@DeltaKroneckerGithub_Clash_92"
      - "@DeltaKroneckerGithub_Clash_94"
      - "@DeltaKroneckerGithub_Clash_96"
      - "@DeltaKroneckerGithub_Clash_98"
      - "@DeltaKroneckerGithub_Clash_100"
      - "@DeltaKroneckerGithub_Clash_102"
      - "@DeltaKroneckerGithub_Clash_104"
      - "@DeltaKroneckerGithub_Clash_106"
      - "@DeltaKroneckerGithub_Clash_108"
      - "@DeltaKroneckerGithub_Clash_111"
      - "@DeltaKroneckerGithub_Clash_113"
=======
      - "@DeltaKroneckerGithub_Clash_266"
      - "@DeltaKroneckerGithub_Clash_268"
      - "@DeltaKroneckerGithub_Clash_270"
      - "@DeltaKroneckerGithub_Clash_272"
      - "@DeltaKroneckerGithub_Clash_274"
      - "@DeltaKroneckerGithub_Clash_276"
      - "@DeltaKroneckerGithub_Clash_278"
      - "@DeltaKroneckerGithub_Clash_280"
      - "@DeltaKroneckerGithub_Clash_282"
      - "@DeltaKroneckerGithub_Clash_284"
      - "@DeltaKroneckerGithub_Clash_286"
      - "@DeltaKroneckerGithub_Clash_288"
      - "@DeltaKroneckerGithub_Clash_290"
      - "@DeltaKroneckerGithub_Clash_293"
      - "@DeltaKroneckerGithub_Clash_295"
      - "@DeltaKroneckerGithub_Clash_297"
      - "@DeltaKroneckerGithub_Clash_299"
      - "@DeltaKroneckerGithub_Clash_301"
      - "@DeltaKroneckerGithub_Clash_303"
      - "@DeltaKroneckerGithub_Clash_305"
>>>>>>> Stashed changes

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
<<<<<<< Updated upstream
      - "@DeltaKroneckerGithub_Clash_92"
      - "@DeltaKroneckerGithub_Clash_94"
      - "@DeltaKroneckerGithub_Clash_96"
      - "@DeltaKroneckerGithub_Clash_98"
      - "@DeltaKroneckerGithub_Clash_100"
      - "@DeltaKroneckerGithub_Clash_102"
      - "@DeltaKroneckerGithub_Clash_104"
      - "@DeltaKroneckerGithub_Clash_106"
      - "@DeltaKroneckerGithub_Clash_108"
      - "@DeltaKroneckerGithub_Clash_111"
      - "@DeltaKroneckerGithub_Clash_113"
=======
      - "@DeltaKroneckerGithub_Clash_266"
      - "@DeltaKroneckerGithub_Clash_268"
      - "@DeltaKroneckerGithub_Clash_270"
      - "@DeltaKroneckerGithub_Clash_272"
      - "@DeltaKroneckerGithub_Clash_274"
      - "@DeltaKroneckerGithub_Clash_276"
      - "@DeltaKroneckerGithub_Clash_278"
      - "@DeltaKroneckerGithub_Clash_280"
      - "@DeltaKroneckerGithub_Clash_282"
      - "@DeltaKroneckerGithub_Clash_284"
      - "@DeltaKroneckerGithub_Clash_286"
      - "@DeltaKroneckerGithub_Clash_288"
      - "@DeltaKroneckerGithub_Clash_290"
      - "@DeltaKroneckerGithub_Clash_293"
      - "@DeltaKroneckerGithub_Clash_295"
      - "@DeltaKroneckerGithub_Clash_297"
      - "@DeltaKroneckerGithub_Clash_299"
      - "@DeltaKroneckerGithub_Clash_301"
      - "@DeltaKroneckerGithub_Clash_303"
      - "@DeltaKroneckerGithub_Clash_305"
>>>>>>> Stashed changes

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
<<<<<<< Updated upstream
      - "@DeltaKroneckerGithub_Clash_92"
      - "@DeltaKroneckerGithub_Clash_94"
      - "@DeltaKroneckerGithub_Clash_96"
      - "@DeltaKroneckerGithub_Clash_98"
      - "@DeltaKroneckerGithub_Clash_100"
      - "@DeltaKroneckerGithub_Clash_102"
      - "@DeltaKroneckerGithub_Clash_104"
      - "@DeltaKroneckerGithub_Clash_106"
      - "@DeltaKroneckerGithub_Clash_108"
      - "@DeltaKroneckerGithub_Clash_111"
      - "@DeltaKroneckerGithub_Clash_113"
=======
      - "@DeltaKroneckerGithub_Clash_266"
      - "@DeltaKroneckerGithub_Clash_268"
      - "@DeltaKroneckerGithub_Clash_270"
      - "@DeltaKroneckerGithub_Clash_272"
      - "@DeltaKroneckerGithub_Clash_274"
      - "@DeltaKroneckerGithub_Clash_276"
      - "@DeltaKroneckerGithub_Clash_278"
      - "@DeltaKroneckerGithub_Clash_280"
      - "@DeltaKroneckerGithub_Clash_282"
      - "@DeltaKroneckerGithub_Clash_284"
      - "@DeltaKroneckerGithub_Clash_286"
      - "@DeltaKroneckerGithub_Clash_288"
      - "@DeltaKroneckerGithub_Clash_290"
      - "@DeltaKroneckerGithub_Clash_293"
      - "@DeltaKroneckerGithub_Clash_295"
      - "@DeltaKroneckerGithub_Clash_297"
      - "@DeltaKroneckerGithub_Clash_299"
      - "@DeltaKroneckerGithub_Clash_301"
      - "@DeltaKroneckerGithub_Clash_303"
      - "@DeltaKroneckerGithub_Clash_305"
>>>>>>> Stashed changes

rules:
  - MATCH,PROXY
