name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@DeltaKroneckerGithub_Clash_2826"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "auto"
    sni: "e9464f45.trauma-2r4.pages.dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1662"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8437d6e8-8492-4ef2-8eb3-0e9ee281882f"
    sni: "ush9pgjbr1t6mxmbwe.jjjiedian6j4tblb.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2450"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "NISHIKUITAN111"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_292"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "dfc0cb9d-f005-41b0-848c-7703bd39d0de"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jp.s3-cloud.org"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "QVkd5uoSbUA7rHVLtIoJB4iRp4l0zuw0H9qzQBh3lHs"
      short-id: "7a3f9e2b1c8d4f6a"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_1358"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_212"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "749a5df1-2d12-45cf-80f3-f85ea6b2e405"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "Fp0-VrMBeaQe9xOrehDYHt0mqTZL-5CdfuMEzoXkOE8"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_46"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "931729a8-3c20-4841-89a1-f18dc9ce0a6f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn7-09.vk-cdnvideo.com"
    client-fingerprint: "chrome"
  - name: "@DeltaKroneckerGithub_Clash_2978"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "e65c6420-e97c-11ed-ae11-1239d0255272"
    sni: "yahoo.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1186"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true
  - name: "@DeltaKroneckerGithub_Clash_1838"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3008"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1332"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "aes-256-cfb"
    password: "qwerREWQ@@"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_564"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "cc976b15-418b-4f0b-89ce-cd685ffbaf20"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "odbiaA-5s0mkehtfrf2SBcrKAMDP1sFjxKHJYdDCKgc"
      short-id: "81"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_2870"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2404"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_462"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "77777777-8a3e-6666-b6d1-a9c5f0e8b3a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fgnix832fx.fx6hsv0.ccwu.cc"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "fgnix832fx.fx6hsv0.ccwu.cc"
  - name: "@DeltaKroneckerGithub_Clash_2582"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "Aimer"
    sni: "epgb.aimercc.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1674"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2604"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2346"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.ignitelimit.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.ignitelimit.com"
  - name: "@DeltaKroneckerGithub_Clash_1318"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true
  - name: "@DeltaKroneckerGithub_Clash_966"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_4"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "749a5df1-2d12-45cf-80f3-f85ea6b2e405"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "google.com"
    reality-opts:
      public-key: "Fp0-VrMBeaQe9xOrehDYHt0mqTZL-5CdfuMEzoXkOE8"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_1692"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "4f4d1167-ef14-4304-9bce-0740472503ef"
    sni: "fr.01.naiun.bilibili.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2252"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2962"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "rYuChHcwQZskq9E0zdoR"
    sni: "vpn5.rnmcnm.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1150"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "2WJbjavFHQv7vgKhyHEMg7oYTLzQ98GqTTU7LmW2ZuCHy9eZLBkojcCygB1GydiWYmDiwhGHun3Xi9Dm4s9Ho9QSnCMeHaPH"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_2826"
      - "@DeltaKroneckerGithub_Clash_1662"
      - "@DeltaKroneckerGithub_Clash_2450"
      - "@DeltaKroneckerGithub_Clash_292"
      - "@DeltaKroneckerGithub_Clash_1358"
      - "@DeltaKroneckerGithub_Clash_212"
      - "@DeltaKroneckerGithub_Clash_46"
      - "@DeltaKroneckerGithub_Clash_2978"
      - "@DeltaKroneckerGithub_Clash_1186"
      - "@DeltaKroneckerGithub_Clash_1838"
      - "@DeltaKroneckerGithub_Clash_3008"
      - "@DeltaKroneckerGithub_Clash_1332"
      - "@DeltaKroneckerGithub_Clash_564"
      - "@DeltaKroneckerGithub_Clash_2870"
      - "@DeltaKroneckerGithub_Clash_2404"
      - "@DeltaKroneckerGithub_Clash_462"
      - "@DeltaKroneckerGithub_Clash_2582"
      - "@DeltaKroneckerGithub_Clash_1674"
      - "@DeltaKroneckerGithub_Clash_2604"
      - "@DeltaKroneckerGithub_Clash_2346"
      - "@DeltaKroneckerGithub_Clash_1318"
      - "@DeltaKroneckerGithub_Clash_966"
      - "@DeltaKroneckerGithub_Clash_4"
      - "@DeltaKroneckerGithub_Clash_1692"
      - "@DeltaKroneckerGithub_Clash_2252"
      - "@DeltaKroneckerGithub_Clash_2962"
      - "@DeltaKroneckerGithub_Clash_1150"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_2826"
      - "@DeltaKroneckerGithub_Clash_1662"
      - "@DeltaKroneckerGithub_Clash_2450"
      - "@DeltaKroneckerGithub_Clash_292"
      - "@DeltaKroneckerGithub_Clash_1358"
      - "@DeltaKroneckerGithub_Clash_212"
      - "@DeltaKroneckerGithub_Clash_46"
      - "@DeltaKroneckerGithub_Clash_2978"
      - "@DeltaKroneckerGithub_Clash_1186"
      - "@DeltaKroneckerGithub_Clash_1838"
      - "@DeltaKroneckerGithub_Clash_3008"
      - "@DeltaKroneckerGithub_Clash_1332"
      - "@DeltaKroneckerGithub_Clash_564"
      - "@DeltaKroneckerGithub_Clash_2870"
      - "@DeltaKroneckerGithub_Clash_2404"
      - "@DeltaKroneckerGithub_Clash_462"
      - "@DeltaKroneckerGithub_Clash_2582"
      - "@DeltaKroneckerGithub_Clash_1674"
      - "@DeltaKroneckerGithub_Clash_2604"
      - "@DeltaKroneckerGithub_Clash_2346"
      - "@DeltaKroneckerGithub_Clash_1318"
      - "@DeltaKroneckerGithub_Clash_966"
      - "@DeltaKroneckerGithub_Clash_4"
      - "@DeltaKroneckerGithub_Clash_1692"
      - "@DeltaKroneckerGithub_Clash_2252"
      - "@DeltaKroneckerGithub_Clash_2962"
      - "@DeltaKroneckerGithub_Clash_1150"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_2826"
      - "@DeltaKroneckerGithub_Clash_1662"
      - "@DeltaKroneckerGithub_Clash_2450"
      - "@DeltaKroneckerGithub_Clash_292"
      - "@DeltaKroneckerGithub_Clash_1358"
      - "@DeltaKroneckerGithub_Clash_212"
      - "@DeltaKroneckerGithub_Clash_46"
      - "@DeltaKroneckerGithub_Clash_2978"
      - "@DeltaKroneckerGithub_Clash_1186"
      - "@DeltaKroneckerGithub_Clash_1838"
      - "@DeltaKroneckerGithub_Clash_3008"
      - "@DeltaKroneckerGithub_Clash_1332"
      - "@DeltaKroneckerGithub_Clash_564"
      - "@DeltaKroneckerGithub_Clash_2870"
      - "@DeltaKroneckerGithub_Clash_2404"
      - "@DeltaKroneckerGithub_Clash_462"
      - "@DeltaKroneckerGithub_Clash_2582"
      - "@DeltaKroneckerGithub_Clash_1674"
      - "@DeltaKroneckerGithub_Clash_2604"
      - "@DeltaKroneckerGithub_Clash_2346"
      - "@DeltaKroneckerGithub_Clash_1318"
      - "@DeltaKroneckerGithub_Clash_966"
      - "@DeltaKroneckerGithub_Clash_4"
      - "@DeltaKroneckerGithub_Clash_1692"
      - "@DeltaKroneckerGithub_Clash_2252"
      - "@DeltaKroneckerGithub_Clash_2962"
      - "@DeltaKroneckerGithub_Clash_1150"

rules:
  - MATCH,PROXY
