name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@DeltaKroneckerGithub_Clash_3691"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_4781"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3605"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_5343"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "bpb-trojan"
    sni: "bPB-worker-PANeL1-e4p.paGes.DeV"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_274"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "19804f6b-3661-4eca-b294-ba37196dab5b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "graph.instagram.com.cyylr.eu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/id-tksi"
      headers:
        Host: "graph.instagram.com.cyylr.eu.cc"
  - name: "@DeltaKroneckerGithub_Clash_1469"
    type: vmess
    server: "127.0.0.1"
    port: 40443
    uuid: "58fe1542-5290-40ad-815a-77707a81afe5"
    alterId: 0
    cipher: "chacha20-poly1305"
    udp: true
    network: ws
    ws-opts:
      path: "/IOebhLMhl1CTbFHbL95myfRX2"
      headers:
        Host: "de2.ping-game.ir"
  - name: "@DeltaKroneckerGithub_Clash_4785"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "kkzh2prsyr2ik47as615"
    sni: "static.rutube.ru"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_4107"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "aeituqOkfYhy"
    sni: "tasnim.andishehnegariran.ir"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_6049"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "Aimer"
    sni: "epms.ambercc.filegear-sg.me"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_840"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "dfc0cb9d-f005-41b0-848c-7703bd39d0de"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "it.s3-cloud.xyz"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "zPi2L9vrl2hkaCTT3lZTzBna-qz6JrteRjDz1i-DsxY"
      short-id: "7a3f9e2b1c8d4f6a"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_6119"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "4cc9bb80-1234-11f0-94b6-1239d0255272"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_4633"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "rYuChHcwQZskq9E0zdoR"
    sni: "vpn5.rnmcnm.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2823"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8800c518-e68a-4441-a45c-cd67855784c8"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1561"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "JzBgepep1p3V6xxmDvpfM2GwmKJM2Gpj9KgRYwKBVwWybMe4iSNVqA4uafdJctEz3Kt5zGNHhryRm9XiQiJXEFxu2826jk7H"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3715"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6cbceb1-901e-44e1-b68e-0199063eb35f"
    sni: "google.com.progt.cf"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_586"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a6f1755f-0140-4bea-8727-0db1bed7c4df"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "juzi.qea.ccwu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: "juzi.qea.ccwu.cc"
  - name: "@DeltaKroneckerGithub_Clash_412"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "0eca1f22-e5a1-4888-a0fa-c2345e87cf2f"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "@DeltaKroneckerGithub_Clash_6181"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "Aimer"
    sni: "ngepz.ambercc.filegear-sg.me"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_5993"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "7d765dd2-617e-4f79-a1d7-9c10184c02b7"
    sni: "sg0001.170203.xyz"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_556"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e43dd231-7c75-4606-80ec-50fbb8335ce7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "3ik9ws7ATJ5dKDY2Fofv9y7_vpFYsTqgOJRxiQKwA3A"
      short-id: "7b233a973c94ca0a"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_4983"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_96"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "3e5da4f6-93c4-4701-911b-1a5091d2430f"
    udp: true
    network: ws
    ws-opts:
      path: "/ws"
  - name: "@DeltaKroneckerGithub_Clash_4579"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "681e1608-5a5f-48fd-add5-1bc17ebf56b2"
    sni: "node2.yuntongclouds.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3089"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "77b19c69-9840-443d-a66b-f08c81b6950a"
    sni: "0601jp7thimghsuy.bpusfaster2.top"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3865"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_6061"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "bpb-trojan"
    sni: "bpb.my79801.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2687"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "/59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true
  - name: "@DeltaKroneckerGithub_Clash_4557"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "cfd8d443-a9de-4966-8d2f-7ad5b994f86a"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1869"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "aes-256-gcm"
    password: "KixLvKzwjekG00rm"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2505"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_4321"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3947"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8e2a3980-4684-11f0-b76c-1239d0255272"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_5227"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_5777"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "bpb-trojan"
    sni: "bpb.my79801.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2335"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true
  - name: "@DeltaKroneckerGithub_Clash_246"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "5d42cfef-0556-4f0c-bfb7-161aef500ab5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lenovoglobal.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "PPZbDAYSwCYnPCF8BxguTFfAAZTnLnzpsHePCkGZYxo"
      short-id: "34"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "@DeltaKroneckerGithub_Clash_672"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a6f1755f-0140-4bea-8727-0db1bed7c4df"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "juzi.qea.ccwu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: "juzi.qea.ccwu.cc"
  - name: "@DeltaKroneckerGithub_Clash_1150"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "c3ec1913-fdd3-4dea-b551-f82d6c2c21ef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "unnes.ac.id.cyylr.eu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/sg-orcl"
      headers:
        Host: "unnes.ac.id.cyylr.eu.cc"
  - name: "@DeltaKroneckerGithub_Clash_3847"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmloud.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2069"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "2022-blake3-aes-256-gcm"
    password: "tEY1W9tCYB6R5Y22378dJ9yh4H4PAZlAM/m31aG1PYM="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_3691"
      - "@DeltaKroneckerGithub_Clash_4781"
      - "@DeltaKroneckerGithub_Clash_3605"
      - "@DeltaKroneckerGithub_Clash_5343"
      - "@DeltaKroneckerGithub_Clash_274"
      - "@DeltaKroneckerGithub_Clash_1469"
      - "@DeltaKroneckerGithub_Clash_4785"
      - "@DeltaKroneckerGithub_Clash_4107"
      - "@DeltaKroneckerGithub_Clash_6049"
      - "@DeltaKroneckerGithub_Clash_840"
      - "@DeltaKroneckerGithub_Clash_6119"
      - "@DeltaKroneckerGithub_Clash_4633"
      - "@DeltaKroneckerGithub_Clash_2823"
      - "@DeltaKroneckerGithub_Clash_1561"
      - "@DeltaKroneckerGithub_Clash_3715"
      - "@DeltaKroneckerGithub_Clash_586"
      - "@DeltaKroneckerGithub_Clash_412"
      - "@DeltaKroneckerGithub_Clash_6181"
      - "@DeltaKroneckerGithub_Clash_5993"
      - "@DeltaKroneckerGithub_Clash_556"
      - "@DeltaKroneckerGithub_Clash_4983"
      - "@DeltaKroneckerGithub_Clash_96"
      - "@DeltaKroneckerGithub_Clash_4579"
      - "@DeltaKroneckerGithub_Clash_3089"
      - "@DeltaKroneckerGithub_Clash_3865"
      - "@DeltaKroneckerGithub_Clash_6061"
      - "@DeltaKroneckerGithub_Clash_2687"
      - "@DeltaKroneckerGithub_Clash_4557"
      - "@DeltaKroneckerGithub_Clash_1869"
      - "@DeltaKroneckerGithub_Clash_2505"
      - "@DeltaKroneckerGithub_Clash_4321"
      - "@DeltaKroneckerGithub_Clash_3947"
      - "@DeltaKroneckerGithub_Clash_5227"
      - "@DeltaKroneckerGithub_Clash_5777"
      - "@DeltaKroneckerGithub_Clash_2335"
      - "@DeltaKroneckerGithub_Clash_246"
      - "@DeltaKroneckerGithub_Clash_672"
      - "@DeltaKroneckerGithub_Clash_1150"
      - "@DeltaKroneckerGithub_Clash_3847"
      - "@DeltaKroneckerGithub_Clash_2069"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_3691"
      - "@DeltaKroneckerGithub_Clash_4781"
      - "@DeltaKroneckerGithub_Clash_3605"
      - "@DeltaKroneckerGithub_Clash_5343"
      - "@DeltaKroneckerGithub_Clash_274"
      - "@DeltaKroneckerGithub_Clash_1469"
      - "@DeltaKroneckerGithub_Clash_4785"
      - "@DeltaKroneckerGithub_Clash_4107"
      - "@DeltaKroneckerGithub_Clash_6049"
      - "@DeltaKroneckerGithub_Clash_840"
      - "@DeltaKroneckerGithub_Clash_6119"
      - "@DeltaKroneckerGithub_Clash_4633"
      - "@DeltaKroneckerGithub_Clash_2823"
      - "@DeltaKroneckerGithub_Clash_1561"
      - "@DeltaKroneckerGithub_Clash_3715"
      - "@DeltaKroneckerGithub_Clash_586"
      - "@DeltaKroneckerGithub_Clash_412"
      - "@DeltaKroneckerGithub_Clash_6181"
      - "@DeltaKroneckerGithub_Clash_5993"
      - "@DeltaKroneckerGithub_Clash_556"
      - "@DeltaKroneckerGithub_Clash_4983"
      - "@DeltaKroneckerGithub_Clash_96"
      - "@DeltaKroneckerGithub_Clash_4579"
      - "@DeltaKroneckerGithub_Clash_3089"
      - "@DeltaKroneckerGithub_Clash_3865"
      - "@DeltaKroneckerGithub_Clash_6061"
      - "@DeltaKroneckerGithub_Clash_2687"
      - "@DeltaKroneckerGithub_Clash_4557"
      - "@DeltaKroneckerGithub_Clash_1869"
      - "@DeltaKroneckerGithub_Clash_2505"
      - "@DeltaKroneckerGithub_Clash_4321"
      - "@DeltaKroneckerGithub_Clash_3947"
      - "@DeltaKroneckerGithub_Clash_5227"
      - "@DeltaKroneckerGithub_Clash_5777"
      - "@DeltaKroneckerGithub_Clash_2335"
      - "@DeltaKroneckerGithub_Clash_246"
      - "@DeltaKroneckerGithub_Clash_672"
      - "@DeltaKroneckerGithub_Clash_1150"
      - "@DeltaKroneckerGithub_Clash_3847"
      - "@DeltaKroneckerGithub_Clash_2069"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_3691"
      - "@DeltaKroneckerGithub_Clash_4781"
      - "@DeltaKroneckerGithub_Clash_3605"
      - "@DeltaKroneckerGithub_Clash_5343"
      - "@DeltaKroneckerGithub_Clash_274"
      - "@DeltaKroneckerGithub_Clash_1469"
      - "@DeltaKroneckerGithub_Clash_4785"
      - "@DeltaKroneckerGithub_Clash_4107"
      - "@DeltaKroneckerGithub_Clash_6049"
      - "@DeltaKroneckerGithub_Clash_840"
      - "@DeltaKroneckerGithub_Clash_6119"
      - "@DeltaKroneckerGithub_Clash_4633"
      - "@DeltaKroneckerGithub_Clash_2823"
      - "@DeltaKroneckerGithub_Clash_1561"
      - "@DeltaKroneckerGithub_Clash_3715"
      - "@DeltaKroneckerGithub_Clash_586"
      - "@DeltaKroneckerGithub_Clash_412"
      - "@DeltaKroneckerGithub_Clash_6181"
      - "@DeltaKroneckerGithub_Clash_5993"
      - "@DeltaKroneckerGithub_Clash_556"
      - "@DeltaKroneckerGithub_Clash_4983"
      - "@DeltaKroneckerGithub_Clash_96"
      - "@DeltaKroneckerGithub_Clash_4579"
      - "@DeltaKroneckerGithub_Clash_3089"
      - "@DeltaKroneckerGithub_Clash_3865"
      - "@DeltaKroneckerGithub_Clash_6061"
      - "@DeltaKroneckerGithub_Clash_2687"
      - "@DeltaKroneckerGithub_Clash_4557"
      - "@DeltaKroneckerGithub_Clash_1869"
      - "@DeltaKroneckerGithub_Clash_2505"
      - "@DeltaKroneckerGithub_Clash_4321"
      - "@DeltaKroneckerGithub_Clash_3947"
      - "@DeltaKroneckerGithub_Clash_5227"
      - "@DeltaKroneckerGithub_Clash_5777"
      - "@DeltaKroneckerGithub_Clash_2335"
      - "@DeltaKroneckerGithub_Clash_246"
      - "@DeltaKroneckerGithub_Clash_672"
      - "@DeltaKroneckerGithub_Clash_1150"
      - "@DeltaKroneckerGithub_Clash_3847"
      - "@DeltaKroneckerGithub_Clash_2069"

rules:
  - MATCH,PROXY
