name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@DeltaKroneckerGithub_Clash_272"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "4b9063e0-3288-44e9-9aac-80fbfce323a0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "dSSDPTK6AHfAdRAXD9i4rzqcNIY65RxlF25UyCKdiyo"
      short-id: "fa"
  - name: "@DeltaKroneckerGithub_Clash_1354"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "vgHT4AF253YLbcGh8WG1jMRX4SFsgYxszwpocdbeaCUoaBDwNoC8SxtaiSHh1Mm51cFhhrMpfrgyyFj71kbE44VnRPcgxPAg"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2256"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "4f4d1167-ef14-4304-9bce-0740472503ef"
    sni: "az.01.naiun.bilibili.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_4128"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2624"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "5a2c16f9"
    sni: "snippets.kkii.eu.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_222"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "931729a8-3c20-4841-89a1-f18dc9ce0a6f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn9-33.vk-cdnvideo.com"
  - name: "@DeltaKroneckerGithub_Clash_1312"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3292"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "6884d714-d3c4-4b49-aa20-767ea92837d6"
    sni: "icecream.955850.xyz"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2504"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "bpb-trojan"
    sni: "fcspring.ggff.net"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1622"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "G5p6ww4o67HB"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_492"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "8546145579"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "978-Yxgtd3AWTVfiXEQqCstdwrT1qgsgleGPIRGQDl8"
      short-id: "bdac121c7debdaba"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_1798"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "blue2024"
    sni: "ha.lii2010.us.kg"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1834"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "3Ldo ,81m[h)3Lb "
    sni: "azaDNeT05.PAgEs.DeV"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_294"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "3994b2e1-d52c-4536-9848-0b63d74560fa"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "q42m1wg11kZLyRtjaKus8T-NNl1vriRG3V1eVTL6ICc"
      short-id: "071d2947bac1"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_2098"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "Aimer"
    sni: "epccf.ambercc.filegear-sg.me"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_4038"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3652"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "bpb-trojan"
    sni: "403b3611-99bc-43B7-88D7-26Ed5d0825A9-3.pageS.dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1318"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true
  - name: "@DeltaKroneckerGithub_Clash_1424"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "3e96ef7d-8637-42c2-ac73-75182196e755"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3550"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "BSs5IAVMQdYuykvDsOYZoa6gNPSGBjAbLL"
    sni: "www.mesaly.click"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1718"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "aes-256-cfb"
    password: "amazonskr05"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1438"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "2CYTbbAxJMWdzMxePpCMDjkub13CDxU2BqaJzb1Zt3HBYGWsfKwNgQKhzEa7uAJut74Bj4fhiwJ6CKFBu4MiQ43QEe9xD2u7"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2040"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "bc7593fe-0604-4fbe-a70bYWVzLTI1Ni1nY2ac5a3ef0-lWNFc1RmRBNk5NQU5KSnga3fa58ac5a3ef0-b4ab-11eb-b65e-1239d0255272"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3506"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3500"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1412"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "aes-256-cfb"
    password: "qwerREWQ@@"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3112"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "ceaea123-1b4b-469b-8358-bcd5f5529305"
    sni: "uk.liangyuandian.top"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_448"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "18afb896-6e4b-403b-b804-714b09b517e5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.icloud.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "tMEkGmuOsuS_cgZYpj2UYBKnni559FZd-poGnH82ck8"
      short-id: "bfb7cb31"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_1082"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true
  - name: "@DeltaKroneckerGithub_Clash_4158"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_28"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "17451fec-af94-4715-8c2f-7f6839130d0a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "apple.com"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "LidllyozUeeSbuzJ0ZfieGoy8YjVzqXX9H2m9whPaG0"
      short-id: "53197c66aef53c44"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_1612"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true
  - name: "@DeltaKroneckerGithub_Clash_568"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "4f51ca84-43ea-4087-b8a2-938e0ccbe27a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "google.com"
    reality-opts:
      public-key: "mDDDyruO33nuqcTS7pZOjd9oOpDHUf0aEv2TQ1DFGV4"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_Clash_1178"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "AmxHJ6RVjmwKnuVo513Wt4Lmwh3i8cdTLXmqF35NnBGL1Ko6AYF7dvNAZNWCcBifbtLJHQxNVcc3PwgtLbxKPLrMhkDRTFab"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2052"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "297b9906-26ef-4d95-9d40-41a221c5bc80"
    sni: "127.0.0.1"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2906"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_3304"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "5a2c16f9"
    sni: "snippets.kkii.eu.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1232"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "chacha20-ietf-poly1305"
    password: "QCXDxuDlTTMD7jtgHUjIoj"
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1766"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "2ee85121-31de-4581-a492-eb00f606e392"
    sni: "hk.freeguard.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_2956"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "9d0a75d2-f747-4afa-b43f-d208af9e8f9a"
    sni: "us01.ssr.ee"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1958"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "auto"
    sni: "dcf741e8.epeius-2gy.pages.dev"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_Clash_1636"
    type: ss
    server: "127.0.0.1"
    port: 40443
    cipher: "none"
    password: "https://t.me/WangCai2🇨🇳"
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: "websocket"
      path: "59fc5f8c-5697-4eb8-acf2-8ae363f203a2/?ed\\=2560"
      host: "woshinidie-et3.pages.dev"
      tls: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_272"
      - "@DeltaKroneckerGithub_Clash_1354"
      - "@DeltaKroneckerGithub_Clash_2256"
      - "@DeltaKroneckerGithub_Clash_4128"
      - "@DeltaKroneckerGithub_Clash_2624"
      - "@DeltaKroneckerGithub_Clash_222"
      - "@DeltaKroneckerGithub_Clash_1312"
      - "@DeltaKroneckerGithub_Clash_3292"
      - "@DeltaKroneckerGithub_Clash_2504"
      - "@DeltaKroneckerGithub_Clash_1622"
      - "@DeltaKroneckerGithub_Clash_492"
      - "@DeltaKroneckerGithub_Clash_1798"
      - "@DeltaKroneckerGithub_Clash_1834"
      - "@DeltaKroneckerGithub_Clash_294"
      - "@DeltaKroneckerGithub_Clash_2098"
      - "@DeltaKroneckerGithub_Clash_4038"
      - "@DeltaKroneckerGithub_Clash_3652"
      - "@DeltaKroneckerGithub_Clash_1318"
      - "@DeltaKroneckerGithub_Clash_1424"
      - "@DeltaKroneckerGithub_Clash_3550"
      - "@DeltaKroneckerGithub_Clash_1718"
      - "@DeltaKroneckerGithub_Clash_1438"
      - "@DeltaKroneckerGithub_Clash_2040"
      - "@DeltaKroneckerGithub_Clash_3506"
      - "@DeltaKroneckerGithub_Clash_3500"
      - "@DeltaKroneckerGithub_Clash_1412"
      - "@DeltaKroneckerGithub_Clash_3112"
      - "@DeltaKroneckerGithub_Clash_448"
      - "@DeltaKroneckerGithub_Clash_1082"
      - "@DeltaKroneckerGithub_Clash_4158"
      - "@DeltaKroneckerGithub_Clash_28"
      - "@DeltaKroneckerGithub_Clash_1612"
      - "@DeltaKroneckerGithub_Clash_568"
      - "@DeltaKroneckerGithub_Clash_1178"
      - "@DeltaKroneckerGithub_Clash_2052"
      - "@DeltaKroneckerGithub_Clash_2906"
      - "@DeltaKroneckerGithub_Clash_3304"
      - "@DeltaKroneckerGithub_Clash_1232"
      - "@DeltaKroneckerGithub_Clash_1766"
      - "@DeltaKroneckerGithub_Clash_2956"
      - "@DeltaKroneckerGithub_Clash_1958"
      - "@DeltaKroneckerGithub_Clash_1636"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_272"
      - "@DeltaKroneckerGithub_Clash_1354"
      - "@DeltaKroneckerGithub_Clash_2256"
      - "@DeltaKroneckerGithub_Clash_4128"
      - "@DeltaKroneckerGithub_Clash_2624"
      - "@DeltaKroneckerGithub_Clash_222"
      - "@DeltaKroneckerGithub_Clash_1312"
      - "@DeltaKroneckerGithub_Clash_3292"
      - "@DeltaKroneckerGithub_Clash_2504"
      - "@DeltaKroneckerGithub_Clash_1622"
      - "@DeltaKroneckerGithub_Clash_492"
      - "@DeltaKroneckerGithub_Clash_1798"
      - "@DeltaKroneckerGithub_Clash_1834"
      - "@DeltaKroneckerGithub_Clash_294"
      - "@DeltaKroneckerGithub_Clash_2098"
      - "@DeltaKroneckerGithub_Clash_4038"
      - "@DeltaKroneckerGithub_Clash_3652"
      - "@DeltaKroneckerGithub_Clash_1318"
      - "@DeltaKroneckerGithub_Clash_1424"
      - "@DeltaKroneckerGithub_Clash_3550"
      - "@DeltaKroneckerGithub_Clash_1718"
      - "@DeltaKroneckerGithub_Clash_1438"
      - "@DeltaKroneckerGithub_Clash_2040"
      - "@DeltaKroneckerGithub_Clash_3506"
      - "@DeltaKroneckerGithub_Clash_3500"
      - "@DeltaKroneckerGithub_Clash_1412"
      - "@DeltaKroneckerGithub_Clash_3112"
      - "@DeltaKroneckerGithub_Clash_448"
      - "@DeltaKroneckerGithub_Clash_1082"
      - "@DeltaKroneckerGithub_Clash_4158"
      - "@DeltaKroneckerGithub_Clash_28"
      - "@DeltaKroneckerGithub_Clash_1612"
      - "@DeltaKroneckerGithub_Clash_568"
      - "@DeltaKroneckerGithub_Clash_1178"
      - "@DeltaKroneckerGithub_Clash_2052"
      - "@DeltaKroneckerGithub_Clash_2906"
      - "@DeltaKroneckerGithub_Clash_3304"
      - "@DeltaKroneckerGithub_Clash_1232"
      - "@DeltaKroneckerGithub_Clash_1766"
      - "@DeltaKroneckerGithub_Clash_2956"
      - "@DeltaKroneckerGithub_Clash_1958"
      - "@DeltaKroneckerGithub_Clash_1636"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_Clash_272"
      - "@DeltaKroneckerGithub_Clash_1354"
      - "@DeltaKroneckerGithub_Clash_2256"
      - "@DeltaKroneckerGithub_Clash_4128"
      - "@DeltaKroneckerGithub_Clash_2624"
      - "@DeltaKroneckerGithub_Clash_222"
      - "@DeltaKroneckerGithub_Clash_1312"
      - "@DeltaKroneckerGithub_Clash_3292"
      - "@DeltaKroneckerGithub_Clash_2504"
      - "@DeltaKroneckerGithub_Clash_1622"
      - "@DeltaKroneckerGithub_Clash_492"
      - "@DeltaKroneckerGithub_Clash_1798"
      - "@DeltaKroneckerGithub_Clash_1834"
      - "@DeltaKroneckerGithub_Clash_294"
      - "@DeltaKroneckerGithub_Clash_2098"
      - "@DeltaKroneckerGithub_Clash_4038"
      - "@DeltaKroneckerGithub_Clash_3652"
      - "@DeltaKroneckerGithub_Clash_1318"
      - "@DeltaKroneckerGithub_Clash_1424"
      - "@DeltaKroneckerGithub_Clash_3550"
      - "@DeltaKroneckerGithub_Clash_1718"
      - "@DeltaKroneckerGithub_Clash_1438"
      - "@DeltaKroneckerGithub_Clash_2040"
      - "@DeltaKroneckerGithub_Clash_3506"
      - "@DeltaKroneckerGithub_Clash_3500"
      - "@DeltaKroneckerGithub_Clash_1412"
      - "@DeltaKroneckerGithub_Clash_3112"
      - "@DeltaKroneckerGithub_Clash_448"
      - "@DeltaKroneckerGithub_Clash_1082"
      - "@DeltaKroneckerGithub_Clash_4158"
      - "@DeltaKroneckerGithub_Clash_28"
      - "@DeltaKroneckerGithub_Clash_1612"
      - "@DeltaKroneckerGithub_Clash_568"
      - "@DeltaKroneckerGithub_Clash_1178"
      - "@DeltaKroneckerGithub_Clash_2052"
      - "@DeltaKroneckerGithub_Clash_2906"
      - "@DeltaKroneckerGithub_Clash_3304"
      - "@DeltaKroneckerGithub_Clash_1232"
      - "@DeltaKroneckerGithub_Clash_1766"
      - "@DeltaKroneckerGithub_Clash_2956"
      - "@DeltaKroneckerGithub_Clash_1958"
      - "@DeltaKroneckerGithub_Clash_1636"

rules:
  - MATCH,PROXY
